# Generated by Django 2.1.3 on 2019-05-24 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='language',
            field=models.TextField(default='C', max_length=200),
            preserve_default=False,
        ),
    ]
