# Generated by Django 2.1.3 on 2019-05-18 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='intersts',
            new_name='Interest',
        ),
    ]
